import { AiCrawlerConfig, AiCrawlerType } from '../config.js';
import { BOT_USER_AGENTS } from './presets.js';

/**
 * Generate robots.txt content based on configuration
 */
export function generateRobotsTxt(config: Partial<AiCrawlerConfig>): string {
  const lines: string[] = [
    '# AI Crawler Guard - robots.txt',
    '# Generated by @ai-crawler-guard',
    '',
  ];

  // Get unique bot types to block
  const botsToBlock = new Set<AiCrawlerType>();

  // Add bots from blockImagesFor
  if (config.blockImagesFor) {
    config.blockImagesFor.forEach((bot) => botsToBlock.add(bot));
  }

  // Add bots from redirectUrls
  if (config.redirectUrls) {
    Object.keys(config.redirectUrls).forEach((bot) =>
      botsToBlock.add(bot as AiCrawlerType)
    );
  }

  // Generate rules for each bot
  botsToBlock.forEach((botType) => {
    if (!botType || botType === 'custom') return;

    const userAgents = BOT_USER_AGENTS[botType];
    if (!userAgents || userAgents.length === 0) return;

    userAgents.forEach((userAgent) => {
      lines.push(`User-agent: ${userAgent}`);

      // If only blocking images
      if (config.blockImagesFor?.includes(botType)) {
        lines.push('Disallow: /images/');
        lines.push('Disallow: /img/');
        lines.push('Disallow: /assets/');
        lines.push('Disallow: /*.jpg$');
        lines.push('Disallow: /*.jpeg$');
        lines.push('Disallow: /*.png$');
        lines.push('Disallow: /*.gif$');
        lines.push('Disallow: /*.webp$');
        lines.push('Disallow: /*.svg$');
      } else {
        // Block everything
        lines.push('Disallow: /');
      }

      lines.push('');
    });
  });

  return lines.join('\n');
}

/**
 * Generate robots.txt for specific bots with custom rules
 */
export function generateCustomRobotsTxt(
  rules: Array<{
    userAgent: string;
    disallow?: string[];
    allow?: string[];
  }>
): string {
  const lines: string[] = [
    '# AI Crawler Guard - robots.txt',
    '# Generated by @ai-crawler-guard',
    '',
  ];

  rules.forEach((rule) => {
    lines.push(`User-agent: ${rule.userAgent}`);

    if (rule.allow) {
      rule.allow.forEach((path) => lines.push(`Allow: ${path}`));
    }

    if (rule.disallow) {
      rule.disallow.forEach((path) => lines.push(`Disallow: ${path}`));
    }

    lines.push('');
  });

  return lines.join('\n');
}

/**
 * Generate a complete robots.txt with both allowed and blocked bots
 */
export function generateFullRobotsTxt(options: {
  allowedBots?: string[];
  blockedBots: Array<{
    type: AiCrawlerType;
    blockImages?: boolean;
  }>;
  sitemap?: string;
}): string {
  const lines: string[] = [
    '# AI Crawler Guard - robots.txt',
    '# Generated by @ai-crawler-guard',
    '',
  ];

  // Add sitemap if provided
  if (options.sitemap) {
    lines.push(`Sitemap: ${options.sitemap}`);
    lines.push('');
  }

  // Allow good bots
  if (options.allowedBots && options.allowedBots.length > 0) {
    lines.push('# Allowed bots');
    options.allowedBots.forEach((bot) => {
      lines.push(`User-agent: ${bot}`);
      lines.push('Allow: /');
      lines.push('');
    });
  }

  // Block AI crawlers
  lines.push('# Blocked AI Crawlers');
  options.blockedBots.forEach(({ type, blockImages }) => {
    if (!type || type === 'custom') return;

    const userAgents = BOT_USER_AGENTS[type];
    if (!userAgents) return;

    userAgents.forEach((userAgent) => {
      lines.push(`User-agent: ${userAgent}`);

      if (blockImages) {
        lines.push('Disallow: /images/');
        lines.push('Disallow: /img/');
        lines.push('Disallow: /*.jpg$');
        lines.push('Disallow: /*.png$');
        lines.push('Disallow: /*.gif$');
      } else {
        lines.push('Disallow: /');
      }

      lines.push('');
    });
  });

  return lines.join('\n');
}
