import { AiCrawlerType } from '../config.js';

/**
 * Bot name mappings for robots.txt User-agent directives
 */
export const BOT_USER_AGENTS: Record<NonNullable<AiCrawlerType>, string[]> = {
  'gptbot': ['GPTBot', 'ChatGPT-User'],
  'claudebot': ['ClaudeBot', 'Claude-Web', 'anthropic-ai'],
  'perplexitybot': ['PerplexityBot'],
  'anthropic-ai': ['anthropic-ai'],
  'google-extended': ['Google-Extended'],
  'bytespider': ['Bytespider'],
  'ccbot': ['CCBot'],
  'custom': [], // Custom bots should be handled separately
};

/**
 * Default robots.txt preset that blocks all AI crawlers
 */
export const defaultAiBotsRobotsTxt = `# Block AI Crawlers
# Generated by @ai-crawler-guard

# OpenAI GPTBot
User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

# Anthropic Claude
User-agent: Claude-Web
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

# Perplexity
User-agent: PerplexityBot
Disallow: /

# Google Extended (Bard/Gemini)
User-agent: Google-Extended
Disallow: /

# ByteDance
User-agent: Bytespider
Disallow: /

# Common Crawl
User-agent: CCBot
Disallow: /

# Other AI scrapers
User-agent: cohere-ai
Disallow: /

User-agent: Omgilibot
Disallow: /

User-agent: Diffbot
Disallow: /

User-agent: FacebookBot
Disallow: /

User-agent: ImagesiftBot
Disallow: /
`;

/**
 * Preset that blocks only image access for AI crawlers
 */
export const blockImagesPreset = `# Block Images for AI Crawlers
# Generated by @ai-crawler-guard

User-agent: GPTBot
Disallow: /images/
Disallow: /img/
Disallow: /assets/
Disallow: /*.jpg$
Disallow: /*.jpeg$
Disallow: /*.png$
Disallow: /*.gif$
Disallow: /*.webp$

User-agent: ClaudeBot
Disallow: /images/
Disallow: /img/
Disallow: /assets/
Disallow: /*.jpg$
Disallow: /*.jpeg$
Disallow: /*.png$
Disallow: /*.gif$
Disallow: /*.webp$

User-agent: PerplexityBot
Disallow: /images/
Disallow: /img/
Disallow: /assets/
Disallow: /*.jpg$
Disallow: /*.jpeg$
Disallow: /*.png$
Disallow: /*.gif$
Disallow: /*.webp$
`;

/**
 * Minimal preset that only blocks GPTBot
 */
export const blockGPTBotOnly = `# Block GPTBot only
User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /
`;
